### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AmirSbss**
Nodejs should be v8 or upper

### CODE REVIEW

**Comment by danyhm** [comment]
well done Amir jan, you are the Iranian Hero.
this patch solves #3

**Comment by FreedomPrevails** [comment]
@AmirSbss I am pretty sure it works on NodeJS 6.0 and higher.

**Comment by danyhm** [comment]
@FreedomPrevails  
I tried installing with the instructions on an Ubuntu 14 LTS, you can see the result in issue #3 . However, I don't know which version of nodejs was being used. thanks for the code anyway it's a huge help to Iranians

**Comment by FreedomPrevails** [comment]
@danyhm you can use "nodejs -v" command to check nodejs version.

**Comment by danyhm** [comment]
@FreedomPrevails  
unfortunately, I applied the patch and right now it gives me v8.11.2
I have to redo the patch which I believe configures the apt-get stuff which I don't want to touch right now since everything is working.

**Pull request closed without merging**
